### ISSUE TITLE
Certain cseqs output blank/wrong midis

### ISSUE THREAD

**Issue by Chubby-Bub** [kr3nshaw/caesar#10]
I am trying to rip music from Animal Crossing: New Leaf's GardenSound.bcsar. Most of the files work great, however some of the TV related soundtracks aren't working. For example, I know SE_TV_08_BGM0 should play a version of K.K. Ragtime, and I can see so in Citric Composer. However the output is a midi with no events except the tempo.
Another problem is with the SE_TV_07 files, which has several cseqs that all output identically to what only the first one should be. Strangely in the latter case, within Citric Composer I can see that these are somehow individual sequences but are all part of the same file, which may have something to do with it.

**Comment by MDHEXT** [comment]
> I am trying to rip music from Animal Crossing: New Leaf's GardenSound.bcsar. Most of the files work great, however some of the TV related soundtracks aren't working. For example, I know SE_TV_08_BGM0 should play a version of K.K. Ragtime, and I can see so in Citric Composer. However the output is a midi with no events except the tempo.
> Another problem is with the SE_TV_07 files, which has several cseqs that all output identically to what only the first one should be. Strangely in the latter case, within Citric Composer I can see that these are somehow individual sequences but are all part of the same file, which may have something to do with it.

the TV soundtracks reference a cwav file, they aren't sequenced. SE_TV_07 is for T.V. SFX, not music-related. The SFX are not sequenced and are streamed as well, stored in a cwav file somewhere.

**Comment by Chubby-Bub** [comment]
> the TV soundtracks reference a cwav file, they aren't sequenced. SE_TV_07 is for T.V. SFX, not music-related. The SFX are not sequenced and are streamed as well, stored in a cwav file somewhere.

You're right, _some_ of them are streamed and with caesar they rip as soundfonts where the instrument is actually a sound effect. But the ones I am referring to are certainly sequenced. These are the ones that have “BGM” in their name. The soundbanks use instrumental samples and not streamed melodies. And some of the TV soundtracks are sequenced music that properly converted to midi. I know these ones should as well.

**Comment by kr3nshaw** [comment]
`SE_TV_08_BGM0.bcseq` doesn't actually contain any note events - just events that cannot be converted, such as jump events. This does not appear to be a bug.

**Comment by Chubby-Bub** [comment]
It has jump events that appear to jump to these note events...? (This is in Citric Composer.)
![image](https://user-images.githubusercontent.com/65587508/106713911-f3dd9780-65af-11eb-8f0c-463aadccd2ca.png)

**Comment by kr3nshaw** [comment]
If it jumps to another sequence, that's beyond my knowledge of the format. You'd be better off just converting the sequence that contains the events that you screenshotted.

**Comment by Chubby-Bub** [comment]
It's the same sequence though.

**Comment by kr3nshaw** [comment]
Okay, I see what you mean. The problem with implementing the jump command is that (unlike the call command) there's the potential for a sequence to use it to enter an infinite loop. It's probably possible to have some kind of infinite loop detection, but it's not at the top of my priority list at the moment.

**Comment by Chubby-Bub** [comment]
Okay, thanks for explaining, at least I kind of know why it happens now.
