### ISSUE TITLE
exporting percussions wrong

### ISSUE THREAD

**Issue by jkrosado** [kr3nshaw/caesar#11]
the percussions don't export right because i never hear them, no matter what app i use, except for when i use a different sound font. happened in 3 apps so far
- streetpass mii plaza
- mii maker (some reason exported percussion even though the track doesn't actually have percussions)
- swapnote
when playing back on macOS, it beeps instead of being silent, too
apparently the swapnote midi has a huge chunk of notes missing

**Comment by kr3nshaw** [comment]
Could you name a specific song from StreetPass Mii Plaza where this happens?

**Comment by milesthecreator** [comment]
Mii Maker has a percussion instrument, specifically instrument 28 in sfx soundfont. In-game, it plays for a few seconds when you create a Mii from a photo.
Swapnote percussion works to me, make sure to switch instrument 127 to drum kit.
Don't know about Streetpass Mii Plaza yet, will edit this comment when I check it out.

**Comment by jkrosado** [comment]
> make sure to switch instrument 127 to drum kit.

how

**Comment by jkrosado** [comment]
> Could you name a specific song from StreetPass Mii Plaza where this happens?

plaza theme 1, bgm_main_mii_max.mid

**Comment by kr3nshaw** [comment]
I don't have any issues playing that song back in SynthFont. Please make sure you're using a suitable tool for working with SoundFonts, i.e. not FL Studio.

**Comment by jkrosado** [comment]
> I don't have any issues playing that song back in SynthFont. Please make sure you're using a suitable tool for working with SoundFonts, i.e. not FL Studio.

synthfont is not available on macOS, any alternatives you know of? none of my programs play it correctly.

**Comment by kr3nshaw** [comment]
I don't use macOS, so I'm not sure. Sorry!
