### ISSUE TITLE
Program won't start

### ISSUE THREAD

**Issue by dog4568** [kr3nshaw/caesar#13]
I just downloaded the latest version but whenever I try to dump files from a bcsar, it always gives me this error.
![Screenshot 2021-10-03 221156](https://user-images.githubusercontent.com/91861206/135787591-d02fd054-bd16-458f-9aad-45c22323e355.png)
I've tried redownloading a couple of times, but I still get the same result.

**Comment by Oreo639** [comment]
You need to install the Microsoft Visual C++ 2015 Redistributable.
https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by kr3nshaw** [comment]
Beat me to it.
