### ISSUE TITLE
[Bug] Health & Safety Information .bcsar

### ISSUE THREAD

**Issue by milesthecreator** [kr3nshaw/caesar#4]
I got the .bcsar for this app but caesar won't extract its contents at all. VGMToolBox and cseq2midi extracted it just fine.

**Comment by kr3nshaw** [comment]
What does the program output if you run it with warnings enabled?

**Comment by fahem1999** [comment]
It doesn't seem to output any warning, it however created a folder but it's empty.
![Screenshot_1](https://user-images.githubusercontent.com/45196539/77292454-c0787e00-6cf9-11ea-9659-164f8ae89b48.png)

**Comment by fahem1999** [comment]
It doesn't seem to output any warning, however it created a new folder but it's empty.
![Screenshot_2](https://user-images.githubusercontent.com/45196539/77292608-16e5bc80-6cfa-11ea-9631-36a50294517e.png)
![Screenshot_3](https://user-images.githubusercontent.com/45196539/77292633-1fd68e00-6cfa-11ea-84f7-a1b340009ca7.png)

**Comment by kr3nshaw** [comment]
Okay, I'm trying to get my hands on the BCSAR so I can test it myself.

**Comment by kr3nshaw** [comment]
Resolved in 0.3.2.

**Comment by milesthecreator** [comment]
I can confirm it works, thank you. :)
