### ISSUE TITLE
Soundfont problem

### ISSUE THREAD

**Issue by milesthecreator** [kr3nshaw/caesar#5]
Whenever I try to play a MIDI track, there's always that one channel that doesn't play any audio at all. Happened to me with several games:
-Swapnote
-NicoNico (A Japanese app)
-Sakura Samurai: Art of the Sword
-Nintendo eShop
-Nintendo Network ID Settings
-Activity Log

I played the track on FL Studio, channel #10 is silent on all the listed games. Same result with playing the track on foobar2000.
![broken channel 10](https://user-images.githubusercontent.com/45196539/88066749-2d543580-cb7f-11ea-8af0-4322cdef8682.png)

This issue doesn't exist when I used this tool: https://github.com/lwyx2016/BCSAR_ExtractToolshttps://github.com/lwyx2016/BCSAR_ExtractTools , though it usually fails to extract anything for some games.

**Comment by kr3nshaw** [comment]
Hey there!

foobar2000 (and presumably FL Studio) expect channel 10 to be some kind of percussion instrument, and so they look for an instrument in bank 128, where percussion instruments usually go. 3DS sequences don't always adhere to this rule, so sometimes there'll be an instrument that's _not_ a percussion instrument on channel 10. If this happens, you'll encounter the problem that you've described. This is the case for the music from Activity Log, at least, but I suspect that it'll be the same for the other games.

This isn't really an issue with caesar, so there's not much I can do about it. I was able to correct the sequences in SynthFont.

**Comment by milesthecreator** [comment]
Alright, thanks for the response. :)

**Comment by TimmSkiller** [comment]
Would someone mind explaining what they did to correct the sequences?

**Comment by kr3nshaw** [comment]
A program like SynthFont allows you to select any instrument for any track, regardless of its channel. For example, you could select a non-percussion instrument for a 'percussion' track, i.e. a track on channel 10.

**Comment by milesthecreator** [comment]
I used Awave Studio to change one of the instruments from "Melodic" to "Drum Kit".
